apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: test-mwh 
  labels:
    app: crd-hook
webhooks:
  - name: test-mwh.mwh.v1
    sideEffects: "None"
    admissionReviewVersions: ["v1beta1","v1"]
    #    namespaceSelector:
    #  matchExpressions:
    #  - key: "managedby"
    #    operator: "In"
    #    values: ["kubeplus"]
    clientConfig:
      service:
        name: crd-hook-service
        namespace: default
        path: "/mutate"
      caBundle: ${CA_BUNDLE}
    rules:
      - operations: [ "CREATE","DELETE"]
        apiGroups: ["workflows.kubeplus", "apps", "extensions", "", "apiextensions.k8s.io", "platformapi.kubeplus"]
        apiVersions: ["v1alpha1", "v1", "v1beta1"]
        resources: ["resourcepolicies", "resourcecompositions", "resourcemonitors", "resourceevents", "pods", "customresourcedefinitions","namespaces","*"]
